"""Section 8 -- Traceability Matrix. Tier 4, fan-in from all 10 technique
agents. This is the one agent in the pipeline that reads full scenario
lists from every Tier 3 agent -- a coverage matrix cannot be built from a
partial view."""
from llm import call_agent
from agents.common import CHAR_LIMIT_RULE, merge_section

SCENARIO_SECTION_IDS = ["11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]

SYSTEM_PROMPT = """You build three traceability tables from scenarios already generated by
ten technique agents: functional requirement -> scenarios, acceptance
criterion -> scenarios, and error code -> scenarios. You do not invent
new scenarios -- you only cross-reference src_refs and titles already
present on each scenario.

RULES:
1. fr_to_scenarios: one row per fdd_requirement (req_id), listing every
   scenario_id (across all ten technique sections in all_scenarios)
   whose src_refs cites that req_id, or whose title/preconditions
   clearly implies that requirement's feature if src_refs is less
   precise. If a requirement has zero matching scenarios, still include
   its row with an empty list -- do not omit it (a coverage gap is
   exactly what this table must surface).
2. ac_to_scenarios: same pattern for each entry in
   fdd_acceptance_scenarios (by name).
3. error_code_to_scenarios: one row per distinct code in
   tdd_error_codes, listing scenario_ids that reference it (mainly from
   the NT/SEC/EH sections). Include a row for any error code mentioned
   as undefined/TBD in issues even if no HTTP code exists yet for it.
4. Do not report coverage gaps. Whether a requirement or acceptance
   criterion has zero scenarios is read straight off your own tables
   afterwards, so a gap list written here would only contradict them.
   Your job is to map accurately; a row with an empty scenario_ids list
   IS the gap.

SELF-CHECK: does every scenario_id you cite actually exist in
all_scenarios? Do not reference one that is not there.

Output strict JSON: fr_to_scenarios (array of {req_id, scenario_ids}),
ac_to_scenarios (array of {acceptance_criterion, scenario_ids}),
error_code_to_scenarios (array of {error_code, scenario_ids}),
assumptions_made (array). JSON only."""


def _row_gaps(rows, key: str, label: str) -> list:
    gaps = []
    for row in rows or []:
        if not isinstance(row, dict):
            continue
        name = str(row.get(key) or "").strip()
        if not name:
            continue
        if not (row.get("scenario_ids") or []):
            gaps.append(f"{label} {name} has no scenario coverage.")
    return gaps


def compute_coverage_gaps(result: dict) -> list:
    """Read the gaps off the matrix rather than asking for them.

    Rule 4 used to say "list any FR or AC row with zero scenarios". In the
    captured run every requirement row had between 8 and 21 scenarios, so
    the correct answer was an empty list -- and the model returned 31
    free-form "no scenarios test X" entries instead, which Agent 10 then
    promoted to the document's top next steps. A gap is a fact about the
    tables directly above it, so derive it."""
    return _row_gaps(
        result.get("fr_to_scenarios"), "req_id", "Requirement"
    ) + _row_gaps(
        result.get("ac_to_scenarios"), "acceptance_criterion", "Acceptance criterion"
    )


def run(state: dict) -> dict:
    fdd = state.get("fdd_sections") or {}
    tdd5 = (state.get("tdd_sections") or {}).get("5") or {}
    section4 = fdd.get("4") or {}
    section11 = fdd.get("11") or {}
    test_sections = state.get("test_sections") or {}

    error_codes = []
    for e in tdd5.get("endpoints") or []:
        if isinstance(e, dict):
            for err in e.get("error_responses") or []:
                if isinstance(err, dict) and err.get("code") is not None:
                    error_codes.append(err.get("code"))

    all_scenarios = {
        sid: (test_sections.get(sid) or {}).get("scenarios") or []
        for sid in SCENARIO_SECTION_IDS
    }

    payload = {
        "fdd_requirements": [
            {"req_id": r.get("req_id"), "feature": r.get("feature")}
            for r in (section4.get("requirements") or [])
            if isinstance(r, dict)
        ],
        "fdd_acceptance_scenarios": [
            s.get("name") for s in (section11.get("scenarios") or []) if isinstance(s, dict)
        ],
        "tdd_error_codes": sorted(set(error_codes)),
        "all_scenarios": all_scenarios,
    }
    result = call_agent(SYSTEM_PROMPT + CHAR_LIMIT_RULE, payload)
    result = dict(result)
    result["coverage_gaps"] = compute_coverage_gaps(result)
    return merge_section(state, "8", "agent8_traceability_matrix", result)
